"""W6-A pre-test classical evidence indexing and fail-closed verification.

This module is read-only with respect to scientific evidence.  It has no codec,
selection, training, channel simulation, or guarded test-loader entry point.
"""

from __future__ import annotations

import hashlib
import json
from collections.abc import Mapping
from pathlib import Path
from typing import Any

from config.params import REPO_ROOT
from baseline.w8_spec_compatibility import load as load_w8_spec_compatibility

SCHEMA_VERSION = 1
W6_ROOT = REPO_ROOT / "results/baseline/w6"
INDEX_PATH = W6_ROOT / "w6_classical_evidence_index.json"
MATRIX_PATH = W6_ROOT / "w6_requirement_matrix.json"
CONTRACT_PATH = REPO_ROOT / "instructions/W6.txt"
INDEX_PREFIX = "w6aindex-"
MATRIX_PREFIX = "w6amatrix-"
CONTRACT_PREFIX = "w6acontract-"
STAGE = "W6_A_PRE_TEST_CLOSURE_PREPARATION"
_EXPECTED_NONDEGENERATE_RATE_COUNT = 4  # literal-ok: frozen G8 terminal closeout count
_MAXIMUM_ALLOWED_OVERHEAD_FRACTION = 0.5  # literal-ok: BR-11/G-8 nondegeneracy threshold
_EXPECTED_BR16_SNR_DB = 7.0  # literal-ok: frozen G8 BR-16 design point
_EXPECTED_BR16_AXIS_PX = 160  # literal-ok: frozen G8 BR-16 encode axis
_EXPECTED_H2_LOW_SNR_DB = 3.0  # literal-ok: frozen G8 H2 window endpoint
_EXPECTED_H2_HIGH_SNR_DB = 7.0  # literal-ok: frozen G8 H2 window endpoint
_EXPECTED_H2_DROP_PP = 79.0  # literal-ok: frozen G8 count-derived point drop
_EXPECTED_PASS_TWO_CALLS = 18  # literal-ok: frozen G8 pass-two call count
_EXPECTED_PASS_TWO_TIES = 95  # literal-ok: frozen G8 pass-two tie count
# W7-C changes only the current normative lambda state after W6-A closed.
# The W6 index remains an immutable pre-G4 snapshot, so these exact successor
# bytes project back to the historical binding rather than regenerating W6.
_W6_FROZEN_NORMATIVE_SHA256 = {
    "normative_spec": "5ff6655bdc24d24f4a78b226b7055300e82b4bd430cb4445be3941aa16d9c9e7",
    "resolved_params": "5eb4c46fb8eed4aa1229a4dcf2f5e42115a68e2d35414fb52962977f930cc7a0",
}
_W7C_CURRENT_NORMATIVE_SHA256 = {
    "normative_spec": "15279f60bd50b00f0d07bc6a5c4355c02d3071b55f087cda412097a8191e466c",
    "resolved_params": "53bb0aff29e999869780a5516f3302f3358170d7980aba0742ce5da8a87b01c5",
}
_W8_CURRENT_NORMATIVE_SHA256 = {
    "normative_spec": "b05a2f04d6b3fa0e8110d0544900c29f823c96c424a75090a092433bb72cc68b",
    "resolved_params": "c5f598e4e9292f831279bed5584cd399c42cc769b6550f8921a7bf94d7e20234",
}
STATUSES = {
    "W6_REQUIRED_AND_SATISFIED",
    "W6_REQUIRED_AND_MISSING",
    "FROZEN_UPSTREAM_INPUT",
    "FUTURE_G12_TEST_EXECUTION",
    "NOT_APPLICABLE_TO_W6",
}


class W6Hold(RuntimeError):
    """A W6 evidence, identity, scope, or scientific-boundary violation."""


def require(condition: bool, message: str) -> None:
    if not condition:
        raise W6Hold(message)


def canonical(value: Any) -> bytes:
    return (json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=True) + "\n").encode("ascii")


def sha256_bytes(raw: bytes) -> str:
    return hashlib.sha256(raw).hexdigest()


def sha256_file(path: Path) -> str:
    return sha256_bytes(path.read_bytes())


def _identified(body: Mapping[str, Any], *, field: str, prefix: str) -> dict[str, Any]:
    value = dict(body)
    value[field] = prefix + sha256_bytes(canonical(value))
    return value


def _verify_identity(value: Mapping[str, Any], *, field: str, prefix: str, label: str) -> None:
    claimed = value.get(field)
    require(isinstance(claimed, str) and claimed.startswith(prefix), f"{label} own-artifact ID is missing or mistyped")
    body = dict(value); body.pop(field, None)
    require(claimed == prefix + sha256_bytes(canonical(body)), f"{label} own-artifact ID content digest differs")


# logical name, path, role, schema, own-ID field, prefix, scientific role,
# provenance role, needed later, custody mode
_BINDINGS = (
    ("normative_spec", "spec/SPEC.md", "normative_specification", None, None, None, "defines W6 scope", "current normative bytes", "W7/W8/W11", "git_exact_bytes"),
    ("resolved_params", "spec/params.generated.yaml", "generated_normative_parameters", None, None, None, "fixes classical and evaluation parameters", "current generated bytes", "W7/W8/W11", "git_exact_bytes"),
    ("g9_spike", "spec/evidence/g9_spike_record.json", "historical_g9_spike_record", None, None, None, "decode throughput and ER-1 projection", "historical exact bytes", "W11 planning only", "git_exact_bytes"),
    ("g1_reference_classifier", "results/reference_classifier/g1_adjudication.json", "g1_adjudication", 1, None, None, "frozen clean scorer", "G-1 adjudication", "W7/W8/W11", "git_exact_bytes_plus_checkpoint_policy"),
    ("g2_physical_layer", "results/baseline/g2/g2_adjudication.json", "g2_adjudication", 1, None, None, "LDPC and packetisation validation", "G-2 adjudication", "W11", "git_exact_bytes"),
    ("w4_integration", "results/baseline/w4/integration_adjudication.json", "w4_integration_adjudication", 2, None, None, "bounded end-to-end classical readiness", "source-bound W4 adjudication", "W11", "git_exact_bytes"),
    ("g8_c_bler_table", "results/baseline/g8_pascal_successor/successor_bler_table.json", "g8_c_pascal_successor_bler_table", 1, "table_id", "g8pblertable-", "measured-only BLER lookup", "successor campaign closeout", "W11", "git_exact_bytes"),
    ("g8_d_handoff", "results/baseline/g8_d/d7_handoff.json", "g8_d_handoff", 1, "artifact_id", "g8dhandoff-", "codec/accounting measurement readiness", "G8_D terminal handoff", "audit only", "git_exact_bytes"),
    ("g8_e_candidate_authority", "results/baseline/g8_e/candidate_authority.json", "g8_e_complete_logical_candidate_authority", 1, "authority_id", "g8eauthority-", "resolves selected candidate IDs", "frozen candidate universe", "W11", "git_exact_bytes"),
    ("g8_e_e4", "results/baseline/g8_e/e2_confessor_successor/runtime/e4_count_derived.json", "g8_e_v3_e4_count_derived_objects", 3, "e4_id", "g8ee4v3-", "validation measured-accuracy inputs", "successor count-derived evidence", "audit only", "git_exact_bytes_large_compact_scientific_record"),
    ("g8_e_e7", "results/baseline/g8_e/e2_confessor_successor/e7_handoff.json", "g8_e_e7_handoff", 1, "handoff_id", "g8ee7handoff-", "G8_E terminal handoff", "campaign/pass-one custody", "audit only", "git_exact_bytes"),
    ("pass_one", "results/baseline/g8_e/pass_one_state.json", "g8_e_pass_one_immutable_completion_record", 1, "state_id", "g8epassone-", "first frozen BR-4 selection", "exact-once history", "audit only", "git_exact_bytes"),
    ("f1_completion", "results/baseline/g8_f/f1_completion.json", "g8_f_f1_completion", 1, "completion_id", "g8ff1completion-", "artifact-corpus availability", "compact corpus custody", "audit only", "git_exact_bytes_plus_worker_object_digests"),
    ("f1_corpus_manifest", "results/baseline/g8_f/f1_corpus_manifest.csv", "g8_f_f1_corpus_manifest", None, None, None, "exact assignment/result partition", "corpus manifest", "audit only", "git_exact_bytes_39809327"),
    ("f2_completion", "results/baseline/g8_f/f2_completion.json", "g8_f_f2_completion", 1, "completion_id", "g8ff2completion-", "artifact scorer training closeout", "F2 exact execution", "audit only", "git_exact_bytes"),
    ("artifact_classifier_freeze", "results/baseline/g8_f/artifact_classifier_freeze.json", "artifact_finetuned_br12_reference_classifier_freeze", 1, "freeze_id", "g8fclassifierfreeze-", "frozen BR-12 scorer", "release/checkpoint custody", "W11", "git_exact_bytes_plus_release_asset"),
    ("f3_aggregate", "results/baseline/g8_f/f3/f3_scoring_aggregate.json", "g8_f_f3_artifact_scorer_aggregate", 1, "aggregate_id", "g8ff3scores-", "cached validation rescoring", "no-reencode F3 closeout", "audit only", "git_exact_bytes"),
    ("pass_two_authorization", "results/baseline/g8_f/pass_two_authorization.json", "g8_f_owner_pass_two_authorization", 1, "authorization_id", "g8fpass2auth-", "authorized exact pass-two scope", "pre-execution authority", "audit only", "git_exact_bytes"),
    ("pass_two_completion", "results/baseline/g8_f/pass_two_state.json", "g8_f_br4_pass_two_immutable_completion", 1, "completion_id", "g8fpass2complete-", "final frozen selected configs", "exact-once terminal selection", "W11", "git_exact_bytes"),
    ("pass_comparison", "results/baseline/g8_f/pass_one_pass_two_comparison.json", "g8_f_pass_one_pass_two_descriptive_comparison", 1, "comparison_id", "g8fpass2compare-", "pass-one/pass-two delta", "selection termination evidence", "audit only", "git_exact_bytes"),
    ("g8_adjudication_input", "results/baseline/g8/g8_validation_adjudication_input.json", "g8_g_validation_adjudication_exact_input", 1, "input_id", "g8ginput-", "ratio/overhead adjudication inputs", "read-only historical cache", "audit only", "git_exact_bytes"),
    ("g8_closeout", "results/baseline/g8/g8_closeout.json", "g8_terminal_validation_side_closeout", 1, "closeout_id", "g8closeout-", "terminal ratios/BR-16/H2/ER-1 strength", "G8 terminal authority", "W7/W8/W11", "immutable_historical_exact_bytes"),
    ("g8_binding_correction", "results/baseline/g8/g8_terminal_binding_metadata_correction.json", "g8_terminal_binding_identity_metadata_correction", 1, "correction_id", "g8bindingcorrection-", "typed own-ID correction", "additive metadata correction", "W7/W8/W11", "git_exact_bytes"),
    ("w5_repaired_completion", "results/learned/w5/w5_gradscaler_accounting_repair_completion.json", "w5_gradscaler_accounting_repair_completion", 1, "repair_id", "w5repaircompletion-", "proves downstream learned/test counters zero", "current W5 authority", "W7", "git_exact_bytes"),
    ("w5_source_manifest", "results/learned/w5/w5_source_manifest_v4.json", "w5_training_critical_source_manifest", 1, "manifest_id", "w5source-", "binds repaired training infrastructure epoch", "current W5 source lineage", "W7", "git_exact_bytes"),
)


def _load_json(path: Path, label: str) -> dict[str, Any]:
    try:
        value = json.loads(path.read_bytes())
    except (OSError, json.JSONDecodeError) as exc:
        raise W6Hold(f"cannot load {label}: {exc}") from exc
    require(isinstance(value, dict), f"{label} is not a JSON object")
    return value


def contract_binding() -> dict[str, Any]:
    raw = CONTRACT_PATH.read_bytes()
    return {"path": str(CONTRACT_PATH.relative_to(REPO_ROOT)), "contract_id": CONTRACT_PREFIX + sha256_bytes(raw), "file_sha256": sha256_bytes(raw)}


def _binding(spec: tuple[Any, ...]) -> dict[str, Any]:
    name, rel, role, schema, id_field, prefix, scientific, provenance, needed, custody = spec
    path = REPO_ROOT / rel
    require(path.is_file(), f"required W6 artifact is missing: {rel}")
    raw = path.read_bytes()
    own_id = None
    if id_field is not None:
        payload = _load_json(path, name)
        require(payload.get("schema_version") == schema, f"{name} schema/version drift")
        require(payload.get("artifact_role") == role, f"{name} artifact role differs")
        own_id = payload.get(id_field)
        require(isinstance(own_id, str) and own_id.startswith(prefix), f"{name} own-artifact ID is missing or mistyped")
    file_sha256 = sha256_bytes(raw)
    if name in _W6_FROZEN_NORMATIVE_SHA256:
        allowed = {
            _W6_FROZEN_NORMATIVE_SHA256[name],
            _W7C_CURRENT_NORMATIVE_SHA256[name],
        }
        if file_sha256 == _W8_CURRENT_NORMATIVE_SHA256[name]:
            # AM-93 is an additive post-W7-C clarification.  Authenticate its
            # exact compatibility record before projecting back to the frozen
            # W6 index bytes; never accept a live hash by name alone.
            load_w8_spec_compatibility(REPO_ROOT)
            allowed.add(_W8_CURRENT_NORMATIVE_SHA256[name])
        require(
            file_sha256 in allowed,
            f"{name} is neither the frozen W6 nor an authenticated successor normative byte image",
        )
        file_sha256 = _W6_FROZEN_NORMATIVE_SHA256[name]
    return {
        "logical_name": name, "path": rel, "artifact_role": role,
        "schema_version": schema, "own_artifact_id_field": id_field,
        "own_artifact_id": own_id, "file_sha256": file_sha256,
        "scientific_role": scientific, "provenance_role": provenance,
        "immutable_or_frozen": True, "needed_again": needed, "custody_mode": custody,
    }


def build_index() -> dict[str, Any]:
    bindings = [_binding(spec) for spec in _BINDINGS]
    by_name = {row["logical_name"]: row for row in bindings}
    closeout = _load_json(REPO_ROOT / by_name["g8_closeout"]["path"], "G8 closeout")
    f1 = _load_json(REPO_ROOT / by_name["f1_completion"]["path"], "F1 completion")
    f2 = _load_json(REPO_ROOT / by_name["f2_completion"]["path"], "F2 completion")
    freeze = _load_json(REPO_ROOT / by_name["artifact_classifier_freeze"]["path"], "artifact classifier freeze")
    f3 = _load_json(REPO_ROOT / by_name["f3_aggregate"]["path"], "F3 aggregate")
    state = _load_json(REPO_ROOT / by_name["pass_two_completion"]["path"], "pass-two state")
    w5 = _load_json(REPO_ROOT / by_name["w5_repaired_completion"]["path"], "W5 repaired completion")
    body = {
        "schema_version": SCHEMA_VERSION,
        "artifact_role": "w6_a_classical_evidence_index",
        "stage": STAGE,
        "terminal_w6_completion_published": False,
        "contract": contract_binding(),
        "bindings": bindings,
        "claims": {
            "operating_points": closeout["operating_points"],
            "er1_strength": closeout["er1_strength"],
            "br16_h2_validation_freeze": closeout["br16_h2_validation_freeze"],
            "classical_nondegeneracy": closeout["classical_nondegeneracy"],
            "f1_corpus": {"corpus_id": f1["corpus_id"], "manifest": f1["corpus_manifest"], "coverage": f1["coverage"], "outcomes": f1["outcomes"], "digests": f1["digests"], "objects": f1["objects"], "storage_custody": f1["storage_custody"], "raw_corpus_needed_again": {"W7": False, "W8": False, "W11": False}},
            "artifact_classifier": {"completion_id": f2["completion_id"], "freeze_id": freeze["freeze_id"], "checkpoint_id": freeze["checkpoint_id"], "selected_epoch_zero_based": f2["selection"]["best_epoch"], "validation_correct": f2["selection"]["best_n_correct"], "validation_total": f2["selection"]["best_n_total"]},
            "f3": {"aggregate_id": f3["aggregate_id"], "row_count": f3["row_count"], "outcomes": f3["outcomes"], "inference_count": f3["artifact_classifier_inference_count"], "scorer": f3["scorer"], "protected_counters": f3["protected_counters"]},
            "pass_two": {"completion_id": state["completion_id"], "authorization_id": state["authorization_id"], "call_count": state["call_count"], "totals": state["totals"], "inputs": state["inputs"], "counters": state["counters"], "selection_passes": state["selection_passes"], "selection_terminates_after_pass": state["selection_terminates_after_pass"]},
            "w5_terminal_authority": {"repair_id": w5["repair_id"], "protected_counters": w5["protected_counters"], "scientific_boundary": w5["scientific_boundary"], "supersedes": w5["supersedes"]},
            "test_split": "SEALED",
            "selected_config_consumption": "immutable_pass_two_lookup_without_selection",
        },
    }
    return _identified(body, field="index_id", prefix=INDEX_PREFIX)


def _entry(requirement: str, obligation: str, status: str, evidence: list[str], rationale: str) -> dict[str, Any]:
    require(status in STATUSES, f"unknown W6 requirement status: {status}")
    return {"requirement": requirement, "obligation": obligation, "status": status, "evidence": evidence, "rationale": rationale}


def matrix_entries() -> list[dict[str, Any]]:
    S, F, U, N = "W6_REQUIRED_AND_SATISFIED", "FUTURE_G12_TEST_EXECUTION", "FROZEN_UPSTREAM_INPUT", "NOT_APPLICABLE_TO_W6"
    return [
        _entry("BR-1", "JPEG 2000 primary source path, measured-size budget and cache implementation", S, ["w4_integration", "g8_d_handoff"], "implemented and validation-proven"),
        _entry("BR-1", "labelled JPEG secondary scientific curve", F, ["normative_spec"], "test-reading secondary curve belongs to the single G-12 campaign"),
        _entry("BR-2", "bit-exact and statistical LDPC validation", U, ["g2_physical_layer"], "G-2 is frozen upstream evidence"),
        _entry("BR-3", "exact matched-k accounting implementation", S, ["g2_physical_layer", "w4_integration"], "packet plans reconcile exact channel uses"),
        _entry("BR-4", "validation tuning, analytic composition and two-pass termination", S, ["pass_one", "f3_aggregate", "pass_two_authorization", "pass_two_completion", "pass_comparison", "g8_closeout"], "pass two is final and exact-once"),
        _entry("BR-4", "actual per-image test channel simulation using frozen configs", F, ["pass_two_completion", "g8_closeout"], "analytic validation selection is not a test result"),
        _entry("BR-5", "typed codec/structural infeasibility implementation", S, ["w4_integration", "g8_e_e4"], "verdict path is implemented and measured on validation"),
        _entry("BR-6", "decode-failure/outage implementation", S, ["w4_integration", "g8_e_e4"], "failures are typed and never skipped"),
        _entry("BR-7", "shared keyed noise identity implementation", S, ["w4_integration", "resolved_params"], "same noise identity is available to future paired execution"),
        _entry("BR-7", "actual paired test noise trajectories", F, ["normative_spec"], "requires model-facing test execution"),
        _entry("BR-8", "frozen clean reference classifier", U, ["g1_reference_classifier"], "G-1 scorer is frozen"),
        _entry("BR-9", "adaptive/fixed-modulation selected-config availability", S, ["pass_two_completion"], "both modes are frozen for every validation SNR"),
        _entry("BR-9", "reported adaptive and fixed-modulation test curves", F, ["normative_spec"], "scientific rows belong to G-12"),
        _entry("BR-10", "CRC, segmentation, filler and rate-matching accounting", S, ["g2_physical_layer", "w4_integration"], "implementation and archived arithmetic are closed"),
        _entry("BR-11", "header/payload/filler semantics and validation overhead table", S, ["w4_integration", "g8_adjudication_input", "g8_closeout"], "nondegeneracy reuses frozen measured overhead"),
        _entry("BR-11", "test-row overhead fields", F, ["resolved_params"], "rows do not exist before G-12"),
        _entry("BR-12", "training-only artifact corpus and frozen artifact scorer", S, ["f1_completion", "f1_corpus_manifest", "f2_completion", "artifact_classifier_freeze"], "F1/F2 are authenticated and closed"),
        _entry("BR-12", "both scorer columns on future reported classical rows", F, ["artifact_classifier_freeze"], "requires future test reconstructions"),
        _entry("BR-13", "frozen measured outage policy and binary per-image handling", S, ["w4_integration", "pass_two_completion"], "selection used measured outage accuracy"),
        _entry("BR-14", "LDPC adapter seam and modulation/CRC conformance", S, ["g2_physical_layer", "w4_integration"], "G-2 and integration checks cover the seam"),
        _entry("BR-15", "adaptation-asymmetry disclosure in final figures/methods", F, ["normative_spec"], "reporting obligation follows future headline figures"),
        _entry("BR-16", "fixed-MCS configuration and H2 validation window freeze", S, ["g8_closeout"], "configuration/window are frozen without test inference"),
        _entry("BR-16", "full-grid fixed-MCS and progressive packetisation sensitivity rows", F, ["g2_physical_layer", "g8_closeout"], "design/config are frozen; reported rows are future campaign output"),
        _entry("ER-1", "full-strength headline classical rows", F, ["g8_closeout"], "ER-1 is full-test at G-12"),
        _entry("ER-1", "strength disposition fixed before test", S, ["g9_spike", "g8_closeout"], "headline full strength; efficiency sweep strength"),
        _entry("ER-3", "classical-only validation sweep and ratios", U, ["g8_adjudication_input", "g8_closeout"], "learned-blind G8 decision is frozen"),
        _entry("ER-5", "schema-exact record emission implementation", S, ["w4_integration", "resolved_params"], "record layer is implemented"),
        _entry("ER-5", "schema-exact final test result rows", F, ["resolved_params"], "no pre-test rows are fabricated"),
        _entry("ER-6", "single-campaign/full-versus-sweep strength policy", S, ["normative_spec", "g8_closeout"], "scope and strength are frozen"),
        _entry("ER-6", "actual test subset/full-split execution", F, ["normative_spec"], "G-12 only"),
        _entry("ER-7", "run/config provenance fields in implementation", S, ["w4_integration", "resolved_params"], "record schema is provenance-capable"),
        _entry("ER-7", "traceability of future thesis numbers", F, ["normative_spec"], "cannot close before results and figures exist"),
        _entry("ER-8", "baseline-strength/no-reinterpretation boundary", S, ["g8_closeout", "w5_repaired_completion"], "frozen baseline remains unchanged"),
        _entry("ER-10", "per-image trace schema and pairing identities", S, ["w4_integration", "resolved_params"], "future runner has trace support"),
        _entry("ER-10", "paired test inference and hypothesis decisions", F, ["normative_spec"], "requires complete G-12 trajectories"),
        _entry("DEC-9", "JPEG 2000 remains primary and JPEG secondary", U, ["normative_spec", "w4_integration"], "codec decision unchanged"),
        _entry("DEC-10", "Sionna adapter plus local packetisation", U, ["g2_physical_layer"], "LDPC decision validated"),
        _entry("DEC-12", "validation selections frozen and test guard sealed", S, ["pass_two_completion", "g8_closeout", "w5_repaired_completion"], "no model-facing test access"),
        _entry("DEC-16", "adaptive baseline and no-handicap rule", U, ["pass_two_completion", "g8_closeout"], "modulation remains adaptive"),
        _entry("G-2", "physical-layer gate", U, ["g2_physical_layer"], "passed upstream"),
        _entry("G-8", "ratios, nondegeneracy, strength, BR-16 and H2", U, ["g8_closeout", "g8_binding_correction"], "terminal G8 is frozen"),
        _entry("G-9", "throughput and one/two-ratio cost projections", U, ["g9_spike"], "historical gate evidence; G8 preserved its disposition"),
        _entry("G-12", "freeze manifest and model-facing test opening", F, ["normative_spec"], "irreversible gate remains unopened"),
        _entry("W6", "typed index/matrix/verifier and frozen-selection consumer", S, ["normative_spec", "pass_two_completion", "w5_repaired_completion"], "W6-A implementation closure preparation"),
        _entry("W7/G-4", "scientific lambda pilot", N, ["w5_repaired_completion"], "explicitly outside W6 and remains zero"),
        _entry("W8", "final learned training", N, ["w5_repaired_completion"], "explicitly outside W6 and remains zero"),
    ]


def build_matrix(index: Mapping[str, Any] | None = None) -> dict[str, Any]:
    current = dict(index or build_index())
    entries = matrix_entries()
    counts = {status: sum(row["status"] == status for row in entries) for status in sorted(STATUSES)}
    body = {
        "schema_version": SCHEMA_VERSION, "artifact_role": "w6_a_requirement_status_matrix",
        "stage": STAGE, "terminal_w6_completion_published": False,
        "index_id": current["index_id"], "index_file_sha256": sha256_bytes(canonical(current)),
        "classification_vocabulary": sorted(STATUSES), "counts": counts, "entries": entries,
        "w6_hold": counts["W6_REQUIRED_AND_MISSING"] != 0,
    }
    return _identified(body, field="matrix_id", prefix=MATRIX_PREFIX)


def verify_index(path: Path = INDEX_PATH, *, invoke_upstream: bool = True) -> dict[str, Any]:
    raw = path.read_bytes(); value = _load_json(path, "W6 evidence index")
    require(raw == canonical(value), "W6 evidence index is not canonical or has schema drift")
    require(value.get("schema_version") == SCHEMA_VERSION and value.get("artifact_role") == "w6_a_classical_evidence_index", "unknown W6 evidence-index schema/version")
    _verify_identity(value, field="index_id", prefix=INDEX_PREFIX, label="W6 evidence index")
    require(value.get("stage") == STAGE and value.get("terminal_w6_completion_published") is False, "W6-A scope/terminal-completion boundary differs")
    expected = build_index()
    require(value == expected, "W6 evidence index does not reproduce from current frozen evidence")
    _verify_inner_claims(value)
    if invoke_upstream:
        _invoke_upstream_verifiers()
    return value


def verify_matrix(path: Path = MATRIX_PATH, *, index: Mapping[str, Any] | None = None) -> dict[str, Any]:
    raw = path.read_bytes(); value = _load_json(path, "W6 requirement matrix")
    require(raw == canonical(value), "W6 requirement matrix is not canonical or has schema drift")
    require(value.get("schema_version") == SCHEMA_VERSION and value.get("artifact_role") == "w6_a_requirement_status_matrix", "unknown W6 requirement-matrix schema/version")
    _verify_identity(value, field="matrix_id", prefix=MATRIX_PREFIX, label="W6 requirement matrix")
    expected = build_matrix(index)
    require(value == expected, "W6 requirement classification or evidence mapping differs")
    require(value["counts"]["W6_REQUIRED_AND_MISSING"] == 0 and value["w6_hold"] is False, "W6-A has a required missing obligation")
    return value


def _verify_inner_claims(index: Mapping[str, Any]) -> None:
    claims = index["claims"]
    op = claims["operating_points"]
    require(op["efficiency_ratio"] == "r_1_24" and op["crossover_ratio"] == op["headline_ratio"] == "r_1_6" and op["low_ratio_operating_point"] == "r_1_24", "G8 selected ratio differs")
    nondegenerate = {row["ratio"]: row for row in claims["classical_nondegeneracy"]}
    for ratio in ("r_1_24", "r_1_6"):
        row = nondegenerate[ratio]
        require(row["feasible_below_half_overhead_ldpc_rate_count"] == _EXPECTED_NONDEGENERATE_RATE_COUNT and row["feasible_below_half_overhead_ldpc_rates"] == ["1/2", "1/3", "2/3", "5/6"] and row["maximum_ceiling_header_fraction_of_budget"] < _MAXIMUM_ALLOWED_OVERHEAD_FRACTION, f"classical nondegeneracy differs at {ratio}")
    strength = claims["er1_strength"]
    require(strength["decision"] == "headline_ratio_only_full_strength_efficiency_at_sweep_strength" and strength["full_strength_ratios"] == ["r_1_6"] and strength["cost_axes"] == ["per_run_against_max_wall_clock_hours_per_run", "aggregate_calendar_time"], "ER-1 strength disposition differs")
    h2 = claims["br16_h2_validation_freeze"]
    require(h2["fixed_configuration"] == {"design_snr_db": _EXPECTED_BR16_SNR_DB, "encode_axis_px": _EXPECTED_BR16_AXIS_PX, "ldpc_rate": "1/2", "modulation": "qam16", "packet_count": 1}, "BR-16 configuration differs")
    require((h2["low_snr_db"], h2["high_snr_db"], h2["classical_drop_pp"]) == (_EXPECTED_H2_LOW_SNR_DB, _EXPECTED_H2_HIGH_SNR_DB, _EXPECTED_H2_DROP_PP), "H2 validation window differs")
    corpus = claims["f1_corpus"]
    require(corpus["manifest"]["rows"] == 50814 and corpus["coverage"]["authenticated_prefix"] == 50814, "F1 corpus assignment count differs")
    require(corpus["outcomes"] == {"materialized_verified_artifact": 44039, "total_assignments": 50814, "typed_image_codec_infeasibility": 6775, "unexpected_or_other": 0}, "F1 corpus outcome counts differ")
    require(corpus["raw_corpus_needed_again"] == {"W7": False, "W8": False, "W11": False}, "F1 future raw-corpus need differs")
    f3 = claims["f3"]
    require(f3["row_count"] == 288000 and f3["inference_count"] == 264000 and f3["outcomes"] == {"codec_infeasibility": 24000, "decode_failure": 0, "delivered": 264000, "structural_infeasibility": 0}, "F3 frozen counts differ")
    require(f3["scorer"]["scorer_identity"] == "br12_artifact_finetuned_reference_classifier", "F3 scorer differs")
    pt = claims["pass_two"]
    require(pt["call_count"] == _EXPECTED_PASS_TWO_CALLS and pt["totals"]["candidates_evaluated"] == 8190 and pt["totals"]["snr_cells_with_selection"] == 378 and pt["totals"]["tie_breaks_applied"] == _EXPECTED_PASS_TWO_TIES, "pass-two terminal totals differ")
    require(pt["selection_passes"] == [1, 2] and pt["selection_terminates_after_pass"] == 2 and pt["counters"]["pass_two"] == 1 and pt["counters"]["pass_three"] == pt["counters"]["test_access"] == pt["counters"]["learned_training"] == 0, "pass-two exact-once/protected boundary differs")
    require(pt["inputs"]["bler_table_id"] == "g8pblertable-69ecc729f3b7dc3d67c0a3a5d8cf071cab927ad0a1e0cd5b18a6bbe674b9126f", "pass-two BLER binding differs")
    require(pt["inputs"]["selection_policy_sha256"] == "6a4ffa98a26ee627f8339f1668f11305e097ca813e246d46a235dbfb2476db0e", "pass-two composition/tie-break policy differs")
    w5 = claims["w5_terminal_authority"]
    require(w5["repair_id"].startswith("w5repaircompletion-") and w5["supersedes"]["completion_id"].startswith("w5completion-"), "repaired W5 terminal authority is not current")
    require(all(value == 0 for value in w5["protected_counters"].values()), "W5 learned/test protected counter is nonzero")
    require(claims["test_split"] == "SEALED", "test split is not sealed")


def _invoke_upstream_verifiers() -> None:
    # Reuse scientific verification logic rather than duplicate its formulas.
    from baseline.g8_f_closeout import verify_closeout as verify_f1
    from baseline.g8_g_closeout import verify_closeout as verify_g8, verify_terminal_binding_correction
    from training.g8_f_f2_closeout import COMPLETION_PATH as F2_COMPLETION, FREEZE_PATH as F2_FREEZE, MONITOR_PATH as F2_MONITOR, verify_compact
    from baseline.g8_f_f3 import verify_aggregate
    from baseline.g8_f_pass_two import verify_authorization, verify_state, verify_comparison
    verify_f1(); verify_compact(F2_COMPLETION, F2_FREEZE, F2_MONITOR)
    verify_aggregate(); verify_authorization(); verify_state(); verify_comparison()
    verify_g8(); verify_terminal_binding_correction()


def verify_all(*, invoke_upstream: bool = True) -> tuple[dict[str, Any], dict[str, Any]]:
    index = verify_index(invoke_upstream=invoke_upstream)
    return index, verify_matrix(index=index)
