#!/usr/bin/env python3
"""Fail-closed, network-free verification of the W3 / G-2 evidence set.

Three things this establishes that are worth stating explicitly, because each one
was a gap rather than an oversight:

**Execution-source binding.** Binding the evidence-file hashes, the measurement
commit and the ancestry measurement -> evidence does not bind the *implementation*
that produced the measurement. `execution_source_manifest.json` closes that: it
records the Git blob id and byte SHA-256 of every source that participated, at the
measurement commit, with a role. Only `runtime` bytes -- the scientific LDPC
implementation under `src/baseline/ldpc/` -- are asserted to be byte-identical
today. `measurement_runner`, `configuration` and `record` bytes are bound as
history, because the current checkout legitimately differs from the measurement
commit for those: `82f6c569f792bf17ff28acd80ed1d516adfc06fa` added a two-line
`sys.path` bootstrap to the measurement runners so they could be invoked directly,
and `spec/params.generated.yaml` is regenerated by `gen_spec_views.py` on every
amendment. Asserting current identity on those would make G-2 self-break on the
next `AM` entry, which is a bookkeeping failure dressed as a scientific one.

**Evidence-commit resolution policy.** The evidence commit is *resolved*, never
recorded: `git log -1 --format=%H -- results/baseline/g2/g2_adjudication.json`
returns the commit that last touched the adjudication file. A file cannot contain
the hash of the commit that adds it, so the alternative to resolution is a
self-referential SHA that is either wrong or manufactured. `g2_adjudication.json`
therefore carries no `evidence_commit` field at all; it previously carried
`"evidence_commit": null`, which read as a missing value rather than a deliberate
one.

**Ancestry, not equality.** The measurement commit must be an ancestor of the
evidence commit. They are deliberately different commits: the campaign runs from a
clean tree, and publishing its outputs is a later commit.
"""

from __future__ import annotations

import csv
import hashlib
import json
import math
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))

from baseline.ldpc.modulation import bits_per_symbol
from config.params import REPO_ROOT, get

DEFAULT_EVIDENCE = REPO_ROOT / "results" / "baseline" / "g2"
REQUIRED_FILES = {
    "resolved_config.json",
    "golden_vector_provenance.json",
    "golden_vector_summary.json",
    "known_answer_summary.json",
    "bler_reference.json",
    "bler_results.csv",
    "packetisation_runtime_check.json",
    "g2_adjudication.json",
}
# The campaign's own outputs are hashed into `g2_adjudication.json`. The source
# manifest is a later, separately verified provenance record over the *inputs*, so
# it is not folded into that hash set -- it verifies against Git and the working
# tree instead, which is strictly stronger than hashing its own bytes.
SOURCE_MANIFEST = "execution_source_manifest.json"

RUNTIME_DIR = "src/baseline/ldpc/"
ROLE_POLICY = {
    "runtime": (
        "Scientific LDPC implementation bytes. MUST still be byte-identical at HEAD, "
        "because a change here means the recorded BLER numbers describe a different "
        "implementation than the one that produced them."
    ),
    "measurement_runner": (
        "Measurement-time bytes of the tools that drove the campaign. Bound as a "
        "historical record only: 82f6c569f792bf17ff28acd80ed1d516adfc06fa added CLI "
        "import bootstrapping to these after the campaign, which is operational and "
        "must not invalidate G-2."
    ),
    "configuration": (
        "Measurement-time configuration and resolved parameters. Historical record "
        "only: spec/params.generated.yaml is regenerated by gen_spec_views.py on "
        "every amendment, so asserting current identity would self-break on the next "
        "AM entry."
    ),
    "record": (
        "Measurement-time packetisation conformance record and the script that "
        "produced it. Historical record only, for the same reason as configuration."
    ),
}
EXPECTED_SOURCES = {
    f"{RUNTIME_DIR}__init__.py": "runtime",
    f"{RUNTIME_DIR}adapter.py": "runtime",
    f"{RUNTIME_DIR}crc.py": "runtime",
    f"{RUNTIME_DIR}modulation.py": "runtime",
    f"{RUNTIME_DIR}rate_matching.py": "runtime",
    f"{RUNTIME_DIR}reference.py": "runtime",
    f"{RUNTIME_DIR}segmentation.py": "runtime",
    f"{RUNTIME_DIR}transport.py": "runtime",
    "tools/run_ldpc_g2.py": "measurement_runner",
    "tools/fetch_ldpc_golden_vectors.py": "measurement_runner",
    "configs/ldpc-g2.yaml": "configuration",
    "spec/params.generated.yaml": "configuration",
    "spec/evidence/check_packetisation.py": "record",
    "spec/evidence/packetisation_record.json": "record",
}
# (source path, artifact that recorded a hash of it at measurement time, field).
# These artifacts were written by the campaign before this manifest existed, so
# agreement is independent corroboration rather than a restatement.
CROSS_CHECKS = (
    ("configs/ldpc-g2.yaml", "resolved_config.json", "config_sha256"),
    ("spec/params.generated.yaml", "resolved_config.json", "params_sha256"),
    ("spec/evidence/packetisation_record.json",
     "packetisation_runtime_check.json", "solver_record_sha256"),
    ("spec/evidence/check_packetisation.py",
     "spec/evidence/packetisation_record.json", "script_sha256"),
)


class VerificationError(RuntimeError):
    pass


def require(condition: bool, message: str) -> None:
    if not condition:
        raise VerificationError(message)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def sha256_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def git(*args: str) -> str:
    result = subprocess.run(
        ["git", "-C", str(REPO_ROOT), *args], capture_output=True, text=True
    )
    if result.returncode:
        raise VerificationError(f"git object/ancestry verification failed: {' '.join(args)}")
    return result.stdout.strip()


def git_bytes(*args: str) -> bytes:
    """Like `git`, for object contents, which must not be decoded or stripped."""
    result = subprocess.run(
        ["git", "-C", str(REPO_ROOT), *args], capture_output=True
    )
    if result.returncode:
        raise VerificationError(f"git object read failed: {' '.join(args)}")
    return result.stdout


def measurement_blobs(commit: str, paths: list[str]) -> dict[str, tuple[str, bytes]]:
    """Return {path: (blob id, bytes)} for `paths` at `commit`, in two Git calls.

    Batched deliberately. Per-path `rev-parse` + `cat-file` is three subprocesses per
    file, and the mutation tests call this once per case, which took the whole test
    suite from 62 s to 169 s before this was batched. A provenance check that makes
    every future run of the suite slower is a check people start skipping.

    A path absent from the tree is simply absent from the result, which is what lets
    the caller report "does not exist at the measurement commit" as itself rather
    than as a hash mismatch.
    """
    listing = git("ls-tree", "-r", "-z", "--format=%(objectname) %(path)", commit, "--", *paths)
    ids: dict[str, str] = {}
    for record in listing.split("\0"):
        if not record.strip():
            continue
        oid, _, path = record.partition(" ")
        ids[path] = oid
    if not ids:
        return {}
    payload = "\n".join(ids.values()) + "\n"
    result = subprocess.run(
        ["git", "-C", str(REPO_ROOT), "cat-file", "--batch"],
        input=payload.encode(), capture_output=True,
    )
    if result.returncode:
        raise VerificationError(f"git object read failed for {commit}")
    contents: dict[str, bytes] = {}
    stream, order = result.stdout, list(ids)
    offset = 0
    for path in order:
        newline = stream.index(b"\n", offset)
        header = stream[offset:newline].split()
        require(len(header) == 3 and header[1] == b"blob",
                f"{path}: not a blob at {commit[:12]}")
        size = int(header[2])
        start = newline + 1
        contents[path] = stream[start:start + size]
        offset = start + size + 1  # trailing newline after each object
    return {path: (ids[path], contents[path]) for path in order}


def manifest_path(evidence_dir: Path = DEFAULT_EVIDENCE) -> Path:
    return evidence_dir / SOURCE_MANIFEST


def current_bytes(source_path: str) -> bytes:
    """Read a source as it exists in the working tree right now.

    A named seam, so the runtime-drift check can be exercised by a test without
    editing the adjudicated implementation on disk. The equivalent seam in the
    transparency-probe verifier exists for the same reason.
    """
    return (REPO_ROOT / source_path).read_bytes()


def verify_sources(evidence_dir: Path, measurement: str) -> dict:
    """Bind the bytes of the implementation that produced the G-2 measurement.

    Returns a summary. Raises `VerificationError` on the first discrepancy: a
    partially verified provenance chain is worth nothing, so this is fail-closed
    like the rest of the file.
    """
    path = manifest_path(evidence_dir)
    manifest = load_json(path)
    require(manifest.get("schema_version") == 1
            and manifest.get("kind") == "g2_execution_source_manifest"
            and manifest.get("gate") == "G-2",
            "wrong execution-source manifest schema or gate")
    require(manifest.get("measurement_commit") == measurement,
            "execution-source manifest binds a different measurement commit")
    require(manifest.get("roles") == ROLE_POLICY,
            "execution-source manifest role policy differs")

    sources = manifest.get("sources")
    require(isinstance(sources, list) and sources, "execution-source manifest has no sources")
    recorded = {}
    for entry in sources:
        require(isinstance(entry, dict) and isinstance(entry.get("path"), str),
                "malformed execution-source entry")
        require(entry["path"] not in recorded,
                f"duplicate execution-source entry: {entry['path']}")
        recorded[entry["path"]] = entry

    missing = sorted(set(EXPECTED_SOURCES) - set(recorded))
    unexpected = sorted(set(recorded) - set(EXPECTED_SOURCES))
    require(not missing, f"execution-source manifest is missing sources: {missing}")
    require(not unexpected, f"execution-source manifest has unexpected sources: {unexpected}")

    # A runtime file added after the campaign would otherwise carry science that
    # nothing binds, so the manifest's runtime role must cover the whole directory
    # at the measurement commit AND at HEAD.
    expected_runtime = {p for p, role in EXPECTED_SOURCES.items() if role == "runtime"}
    for commit, label in ((measurement, "the measurement commit"), ("HEAD", "HEAD")):
        listed = set(git("ls-tree", "-r", "--name-only", commit, "--", RUNTIME_DIR).splitlines())
        require(listed == expected_runtime,
                f"{RUNTIME_DIR} at {label} differs from the bound runtime set: "
                f"missing={sorted(expected_runtime - listed)}, "
                f"unexpected={sorted(listed - expected_runtime)}")

    readjudicated = {
        entry.get("path")
        for entry in manifest.get("readjudications", [])
        if isinstance(entry, dict)
    }
    at_measurement = measurement_blobs(measurement, sorted(EXPECTED_SOURCES))
    absent = sorted(set(EXPECTED_SOURCES) - set(at_measurement))
    require(not absent,
            f"expected sources do not exist at the measurement commit: {absent}")

    drifted = []
    for source_path, role in sorted(EXPECTED_SOURCES.items()):
        entry = recorded[source_path]
        require(entry.get("role") == role,
                f"{source_path}: manifest role {entry.get('role')!r} is not {role!r}")
        oid, content = at_measurement[source_path]
        require(oid == entry.get("measurement_blob"),
                f"{source_path}: recorded Git blob does not match the measurement commit")
        require(sha256_bytes(content) == entry.get("measurement_sha256"),
                f"{source_path}: recorded byte SHA-256 does not match the measurement commit")
        require(len(content) == entry.get("measurement_bytes"),
                f"{source_path}: recorded byte length does not match the measurement commit")
        if role != "runtime":
            continue
        require((REPO_ROOT / source_path).is_file(),
                f"{source_path}: adjudicated G-2 runtime is absent")
        if sha256_bytes(current_bytes(source_path)) != entry["measurement_sha256"]:
            drifted.append(source_path)
    unexplained = sorted(set(drifted) - readjudicated)
    require(not unexplained,
            "HOLD — G-2 runtime differs from adjudicated implementation: "
            f"{unexplained}. No G-2 re-adjudication is recorded for these paths.")

    # The manifest is generated from Git, so on its own it only proves "these were
    # the bytes at that commit". These four hashes were recorded independently by
    # the campaign itself, in artifacts written before this manifest existed, so
    # agreement means the manifest binds the bytes the measurement actually loaded
    # rather than merely the bytes at a commit someone nominated.
    for source_path, artifact, field in CROSS_CHECKS:
        # A bare filename is a G-2 evidence artifact; anything with a separator is
        # repository-relative.
        location = REPO_ROOT / artifact if "/" in artifact else evidence_dir / artifact
        require(load_json(location).get(field) == recorded[source_path]["measurement_sha256"],
                f"{source_path}: measurement bytes disagree with the {field} that "
                f"{artifact} recorded at measurement time")

    roles = sorted({entry["role"] for entry in sources})
    return {"sources": len(sources), "roles": roles, "runtime_readjudicated": sorted(readjudicated)}


def load_json(path: Path) -> dict:
    try:
        value = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError) as exc:
        raise VerificationError(f"invalid evidence JSON: {path.name}") from exc
    require(isinstance(value, dict), f"{path.name} must contain an object")
    return value


def _crossing(rows: list[dict], system: str, modulation: str, target: float) -> float:
    points = sorted(
        (float(row["esn0_db"]), float(row["bler"]))
        for row in rows
        if row["system"] == system and row["modulation"] == modulation
    )
    for (x0, y0), (x1, y1) in zip(points, points[1:], strict=False):
        if y0 >= target >= y1 and y0 > 0 and y1 > 0:
            fraction = (math.log10(target) - math.log10(y0)) / (
                math.log10(y1) - math.log10(y0)
            )
            return x0 + fraction * (x1 - x0)
    raise VerificationError(f"{system}/{modulation}: insufficient simulation cells")


def verify(
    evidence_dir: Path = DEFAULT_EVIDENCE, *, require_evidence_commit: bool = True
) -> dict:
    evidence_dir = evidence_dir.resolve()
    expected_files = REQUIRED_FILES | {SOURCE_MANIFEST}
    actual_files = {path.name for path in evidence_dir.iterdir() if path.is_file()}
    require(actual_files == expected_files,
            f"G-2 evidence file set differs: missing={sorted(expected_files-actual_files)}, "
            f"unexpected={sorted(actual_files-expected_files)}")
    resolved = load_json(evidence_dir / "resolved_config.json")
    golden_provenance = load_json(evidence_dir / "golden_vector_provenance.json")
    golden = load_json(evidence_dir / "golden_vector_summary.json")
    known = load_json(evidence_dir / "known_answer_summary.json")
    reference = load_json(evidence_dir / "bler_reference.json")
    packet = load_json(evidence_dir / "packetisation_runtime_check.json")
    adjudication = load_json(evidence_dir / "g2_adjudication.json")

    require(adjudication.get("schema_version") == 1 and adjudication.get("gate") == "G-2",
            "wrong G-2 adjudication schema or gate")
    measurement = adjudication.get("measurement_commit")
    require(isinstance(measurement, str) and len(measurement) == 40,
            "dirty or unreachable measurement commit")
    git("cat-file", "-e", f"{measurement}^{{commit}}")
    require(resolved.get("measurement_commit") == measurement
            and resolved.get("measurement_dirty") is False
            and adjudication.get("measurement_dirty") is False,
            "dirty or inconsistent measurement commit")
    # Resolved, never recorded -- see this module's docstring. A stored value would
    # have to be either self-referential or wrong, so carrying the key at all (even
    # as null) misrepresents a deliberate policy as a missing field.
    require("evidence_commit" not in adjudication,
            "g2_adjudication.json records an evidence_commit; it is resolved through "
            "Git path history instead")
    if require_evidence_commit:
        relative = (evidence_dir / "g2_adjudication.json").relative_to(REPO_ROOT)
        evidence_commit = git("log", "-1", "--format=%H", "--", str(relative))
        require(bool(evidence_commit), "G-2 evidence commit is unreachable")
        git("cat-file", "-e", f"{evidence_commit}^{{commit}}")
        git("merge-base", "--is-ancestor", measurement, evidence_commit)
    sources = verify_sources(evidence_dir, measurement)

    expected_hashes = adjudication.get("evidence_files")
    require(isinstance(expected_hashes, dict)
            and set(expected_hashes) == REQUIRED_FILES - {"g2_adjudication.json"},
            "evidence hash manifest differs")
    for name, expected in expected_hashes.items():
        require(sha256(evidence_dir / name) == expected, f"{name} hash mismatch")

    require(resolved.get("standard") == get("baseline.ldpc_standard")
            and resolved.get("standard_version") == get("baseline.ldpc_standard_version"),
            "wrong standards version")
    require(resolved.get("sionna_version") == str(get("baseline.ldpc_impl_version")),
            "wrong Sionna version")
    require(not any(resolved.get("test_split_access", {}).values()), "test-split access")

    require(golden_provenance.get("source_rung")
            == golden.get("source_rung")
            == int(get("baseline.ldpc_golden_vector_source_rung")) == 2,
            "wrong golden-vector source rung")
    require(golden_provenance.get("asset_sha256")
            == golden.get("asset_sha256")
            == get("baseline.ldpc_golden_vector_asset_sha256"),
            "wrong golden-vector source checksum")
    expected_alignment = "remove_filler_marker_254_only_input_already_2Z_punctured"
    require(golden_provenance.get("alignment") == golden.get("alignment") == expected_alignment,
            "wrong vector alignment")
    require(golden.get("pass") is True and golden["offline_floor"]["mismatches"] == 0,
            "golden or offline fixture mismatch")
    require(all(
        case["encoder_mismatches"] == case["rate_matched_mismatches"] == 0
        and case["selected_lifting_size"] == case["lifting_size"]
        for case in golden["cases"]
    ), "wrong base graph or lifting size")

    cfg = get("baseline.ldpc_bler_reference")
    require(reference.get("name") == get("baseline.ldpc_bler_reference_source")
            and reference.get("commit") == cfg["commit"]
            and reference.get("archive_sha256") == cfg["archive_sha256"],
            "wrong BLER reference checksum or identity")
    require(reference.get("licence") == cfg["licence"]
            and reference.get("reconstruction") == cfg["reconstruction"],
            "wrong BLER reference source rung or reconstruction")
    settings = reference.get("settings", {})
    for key in ("k", "n", "base_graph", "lifting_size", "rate", "source_snr_convention"):
        require(settings.get(key) == cfg[key], f"wrong reference {key}")
    require(reference.get("decoder_offset") == get("baseline.ldpc_decoder_offset"),
            "wrong decoder offset")
    require(reference.get("iterations") == get("baseline.ldpc_max_iters"),
            "wrong decoder iteration count")

    require(known.get("pass") is True, "wrong mapper, interleaver, CRC, or LLR sign")
    require(set(known.get("crc", {})) == set(get("baseline.crc_spec")), "missing CRC")
    require(all(
        item.get("pass") is True and item.get("actual") == item.get("expected")
        for item in known["crc"].values()
    ), "wrong CRC")
    require(set(known.get("modulation", {})) == set(get("baseline.modulations")),
            "missing modulation")
    for modulation, result in known["modulation"].items():
        require(result["labels_recovered"] and result["sign_flip_detected"],
                f"{modulation}: LLR-sign error")
        require(result["disabled_interleaver_detected"],
                f"{modulation}: wrong mapper or interleaver")

    with (evidence_dir / "bler_results.csv").open(newline="") as handle:
        rows = list(csv.DictReader(handle))
    expected_cells = {
        (system, modulation, float(snr))
        for system in ("reference", "sionna")
        for modulation in get("baseline.modulations")
        for snr in cfg["snr_grid_ebn0_db"][modulation]
    }
    actual_cells = {
        (row["system"], row["modulation"], float(row["ebn0_db"])) for row in rows
    }
    require(actual_cells == expected_cells and len(rows) == len(expected_cells),
            "missing modulation or insufficient simulation cells")
    for row in rows:
        blocks = int(row["blocks"])
        k = int(row["k"])
        bit_errors, block_errors = int(row["bit_errors"]), int(row["block_errors"])
        require(blocks == int(cfg["blocks_per_snr"]), "insufficient simulation blocks")
        require(float(row["ber"]) == bit_errors / (blocks * k)
                and float(row["bler"]) == block_errors / blocks,
                "BER/BLER arithmetic mismatch")
        q_m = bits_per_symbol(row["modulation"])
        expected_es = float(row["ebn0_db"]) + 10 * math.log10(float(cfg["rate"]) * q_m)
        require(abs(float(row["esn0_db"]) - expected_es) < 1e-12,
                "wrong SNR conversion")
        require(int(row["n"]) == int(cfg["n"])
                and int(row["base_graph"]) == int(cfg["base_graph"])
                and int(row["lifting_size"]) == int(cfg["lifting_size"]),
                "wrong base graph or lifting size")
        require(float(row["offset"]) == get("baseline.ldpc_decoder_offset"),
                "wrong decoder offset")
        require(int(row["iterations"]) == get("baseline.ldpc_max_iters"),
                "wrong decoder iteration count")

    target = float(cfg["waterfall_target_bler"])
    tolerance = float(get("evaluation.ber_match_tolerance_db"))
    require(adjudication.get("statistic") == get("evaluation.ber_match_statistic")
            and adjudication.get("target_bler") == target
            and adjudication.get("tolerance_db") == tolerance,
            "wrong comparison statistic")
    require(set(adjudication.get("waterfalls", {})) == set(get("baseline.modulations")),
            "missing modulation waterfall")
    for modulation, recorded in adjudication["waterfalls"].items():
        ref = _crossing(rows, "reference", modulation, target)
        dut = _crossing(rows, "sionna", modulation, target)
        displacement = dut - ref
        require(abs(recorded["reference_waterfall_esn0_db"] - ref) < 1e-12
                and abs(recorded["sionna_waterfall_esn0_db"] - dut) < 1e-12
                and abs(recorded["displacement_db"] - displacement) < 1e-12,
                f"{modulation}: waterfall displacement arithmetic mismatch")
        require(abs(displacement) <= tolerance and recorded["pass"] is True,
                f"{modulation}: BLER displacement above 0.5 dB")
        conversion = adjudication["snr_conversion"][modulation]
        require(
            abs(conversion["additive_db"]
                - 10 * math.log10(float(cfg["rate"]) * bits_per_symbol(modulation))) < 1e-12,
            "wrong SNR conversion",
        )

    require(packet.get("pass") is True and not packet.get("mismatches"),
            "packetisation mismatch")
    require(packet.get("configurations") == 216 and packet.get("proof_obligations") == 144
            and packet.get("feasible") == 215,
            "packetisation grid count mismatch")
    require(packet.get("expected_structural_infeasibility") == [{
        "tag": "cifar10/r_1_48/bpsk/1/3",
        "reason": "no_legal_byte_aligned_A_within_nominal_budget",
    }], "unexplained structural infeasibility")
    require(packet.get("progressive_design") == get("baseline.progressive_packetisation_sensitivity")
            and packet.get("progressive_design_executed") is False,
            "progressive packetisation design mismatch")

    components = adjudication.get("components", {})
    require(components and all(components.values()) and adjudication.get("verdict") == "PASS",
            "G-2 component verdict is not a consistent PASS")
    return {
        "verdict": "PASS",
        "measurement_commit": measurement,
        "waterfalls": adjudication["waterfalls"],
        "rows": len(rows),
        "test_split_access": False,
        "sources": sources["sources"],
        "source_roles": sources["roles"],
    }


def main() -> int:
    try:
        result = verify()
    except VerificationError as exc:
        print(f"G-2 adjudication verification FAILED: {exc}", file=sys.stderr)
        return 1
    print(
        f"G-2 adjudication verification PASS: measurement={result['measurement_commit'][:12]}, "
        f"rows={result['rows']}, test_split_access=0, "
        f"sources={result['sources']} ({'/'.join(result['source_roles'])})"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
